### ISSUE TITLE
Run时遇到一个Command错误

### ISSUE THREAD

**Issue by 54853315** [woooowen/Top4Swift#2]
<unknown>:0: error: no such file or directory: '/Volumes/1/Downloads/ENSwiftSideMenu-master 2/Library/ENSideMenuNavigationController.swift'
<unknown>:0: error: no such file or directory: '/Volumes/1/Downloads/ENSwiftSideMenu-master 2/Library/ENSideMenu.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

**Comment by woooowen** [comment]
使用Top4Swift.xcodeproj 打开项目

**Comment by 54853315** [comment]
呃，还是一样

**Comment by woooowen** [comment]
非常抱歉,我引入了一个文件,但是没有把文件放入项目里面,目前已经fix,你重新下载一下吧,如果你还愿意下载的话.....非常抱歉

**Comment by 54853315** [comment]
呵呵，没事。我再下个试试~
